version: '3.5'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=demetra_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
